spring:
  datasource:
        url: jdbc:mysql://localhost:3306/reservation_system?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Europe/Warsaw
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: komputerek
  jpa:
    show-sql: true
    hibernate:
        ddl-auto: update

  thymeleaf:
    cache: false
    check-template: true
    check-template-location: true
    servlet:
      content-type: text/html
    enabled: true
    encoding: utf-8
    mode: HTML
    prefix: classpath:/templates/
    suffix: .html